/**
 * Docker lifecycle adapter for bounded logs and confirmed stop/remove.
 *
 * Docker stop/remove are destructive and require BOTH a policy grant
 * (enforced by the execution service against the effective config) and a
 * fresh per-action confirmation token. This adapter enforces the second
 * half: the caller must present a confirmation that names the exact target
 * ID and action; noninteractive callers receive a typed
 * `confirmation-required` result and can never bypass the gate.
 *
 * Only read-only discovery/inspection and these two destructive primitives
 * exist here. The locked {@link DockerAdapter} deliberately has no mutation
 * surface; this module is the sole owner of stop/remove/logs.
 */
import type { ProcessRunner } from "./process-runner.js";
import { RuntimeError } from "../errors.js";
import type { DockerContainer } from "./docker-adapter.js";

export type LifecycleAction = "stop" | "remove";

export interface LifecycleConfirmation {
  /** Fresh token generated by the interactive caller for this action+target. */
  readonly token: string;
  readonly action: LifecycleAction;
  readonly containerId: string;
}

export interface ConfirmationRequiredResult {
  readonly status: "confirmation-required";
  readonly action: LifecycleAction;
  readonly containerId: string;
  readonly containerName: string;
  /** What the operator must type to proceed (never rendered with secrets). */
  readonly instruction: string;
}

export interface LifecycleOutcome {
  readonly status: "done";
  readonly action: LifecycleAction;
  readonly containerId: string;
}

export type LifecycleResult = ConfirmationRequiredResult | LifecycleOutcome;

export interface DockerLifecycleAdapter {
  /** Bounded `docker logs --tail <lines> <id>`; output is not parsed. */
  logs(id: string, options?: { tail?: number; signal?: AbortSignal }): Promise<{ exitCode: number | null; output: string; truncated: boolean }>;

  /** Stop a resolved unique container after a matching fresh confirmation. */
  stop(
    container: DockerContainer,
    confirmation: LifecycleConfirmation | undefined,
  ): Promise<LifecycleResult>;

  /** Remove a resolved unique container after a matching fresh confirmation. */
  remove(
    container: DockerContainer,
    confirmation: LifecycleConfirmation | undefined,
  ): Promise<LifecycleResult>;
}

export class NodeDockerLifecycleAdapter implements DockerLifecycleAdapter {
  public constructor(
    private readonly runner: ProcessRunner,
    private readonly options: {
      readonly dockerPath: string;
      readonly env: Readonly<Record<string, string>>;
      readonly cwd: string;
      readonly maxOutputBytes?: number;
    },
  ) {}

  public async logs(
    id: string,
    options: { tail?: number; signal?: AbortSignal } = {},
  ): Promise<{ exitCode: number | null; output: string; truncated: boolean }> {
    if (id.length === 0) {
      throw new RuntimeError({
        kind: "no-candidate",
        message: "Cannot read logs for an empty container ID.",
      });
    }
    const tail = options.tail ?? 200;
    const chunks: Buffer[] = [];
    try {
      const result = await this.runner.exec(this.options.dockerPath, ["logs", "--tail", String(tail), id], {
        cwd: this.options.cwd,
        env: { ...this.options.env },
        maxOutputBytes: this.options.maxOutputBytes ?? 256 * 1024,
        timeoutMs: 30_000,
        ...(options.signal !== undefined ? { signal: options.signal } : {}),
        onData: (chunk) => chunks.push(chunk),
      });
      return {
        exitCode: result.exitCode,
        output: Buffer.concat(chunks).toString("utf8"),
        truncated: result.truncated,
      };
    } catch (error) {
      this.rethrowMapped(error);
    }
    throw new RuntimeError({ kind: "unexpected", message: "unreachable logs path" });
  }

  public async stop(
    container: DockerContainer,
    confirmation: LifecycleConfirmation | undefined,
  ): Promise<LifecycleResult> {
    return this.destructive("stop", container, confirmation, ["stop", container.id]);
  }

  public async remove(
    container: DockerContainer,
    confirmation: LifecycleConfirmation | undefined,
  ): Promise<LifecycleResult> {
    return this.destructive("remove", container, confirmation, ["rm", "-f", container.id]);
  }

  private async destructive(
    action: LifecycleAction,
    container: DockerContainer,
    confirmation: LifecycleConfirmation | undefined,
    argv: readonly string[],
  ): Promise<LifecycleResult> {
    if (!this.isFreshConfirmation(action, container.id, confirmation)) {
      return {
        status: "confirmation-required",
        action,
        containerId: container.id,
        containerName: container.name,
        instruction: `Type "confirm ${action} ${container.id.slice(0, 12)}" to proceed.`,
      };
    }
    try {
      const result = await this.runner.exec(this.options.dockerPath, [...argv], {
        cwd: this.options.cwd,
        env: { ...this.options.env },
        maxOutputBytes: this.options.maxOutputBytes ?? 64 * 1024,
        timeoutMs: 60_000,
      });
      if (result.exitCode !== 0) {
        throw new RuntimeError({
          kind: "devcontainer-cli-failure",
          message: `docker ${action} failed with exit ${result.exitCode}.`,
          exitCode: result.exitCode,
          remedy: "Check Docker daemon reachability and the container state.",
        });
      }
      return { status: "done", action, containerId: container.id };
    } catch (error) {
      this.rethrowMapped(error);
    }
    throw new RuntimeError({ kind: "unexpected", message: "unreachable destructive path" });
  }

  /**
   * Confirmation must name the exact action and target ID. The token is
   * opaque to this adapter; freshness is a caller contract (the execution
   * service generates it interactively and never reuses it).
   */
  private isFreshConfirmation(
    action: LifecycleAction,
    containerId: string,
    confirmation: LifecycleConfirmation | undefined,
  ): boolean {
    if (confirmation === undefined) return false;
    return (
      confirmation.action === action &&
      confirmation.containerId === containerId &&
      confirmation.token.length >= 1
    );
  }

  private rethrowMapped(error: unknown): never {
    if (error instanceof RuntimeError && error.kind === "executable-missing") {
      throw new RuntimeError({
        kind: "daemon-unavailable",
        message: `Docker executable '${this.options.dockerPath}' is unavailable.`,
        cause: error,
        remedy: "Install Docker or set dockerPath in configuration.",
      });
    }
    if (error instanceof RuntimeError && error.kind === "spawn-permission-denied") {
      throw new RuntimeError({
        kind: "authorization-denied",
        message: `Docker spawn was denied for '${this.options.dockerPath}'.`,
        cause: error,
        remedy: "Check operator privileges for the Docker executable.",
      });
    }
    throw error;
  }
}
